#!/usr/bin/env bash
# Runs the tests with coverage and fails unless every line in lib/ is covered.
#
# The Dart VM only reports libraries that some test loads, so an untested file
# would be missing from the report instead of showing up as uncovered. A
# generated test imports every library in lib/ to close that gap.
set -euo pipefail

cd "$(dirname "$0")/.."

all_libraries_test=test/all_libraries_test.dart
lcov=coverage/lcov.info

trap 'rm -f "$all_libraries_test"' EXIT
{
  echo '// Generated by tool/coverage.sh and deleted after the run.'
  echo '// ignore_for_file: unused_import'
  find lib -name '*.dart' | sort | sed "s|^lib/\(.*\)$|import 'package:pubup/\1';|"
  echo "import 'package:test/test.dart';"
  echo
  echo "void main() => test('loads every library in lib/', () {});"
} > "$all_libraries_test"

rm -f "$lcov"
dart test --coverage-path="$lcov"

awk -v root="$(pwd -P)/" '
  /^SF:/ {
    file = substr($0, 4)
    if (index(file, root) == 1) file = substr(file, length(root) + 1)
    next
  }
  /^DA:/ && file ~ /^lib\// {
    split(substr($0, 4), line, ",")
    total++
    if (line[2] == 0) {
      missed++
      print "Not covered: " file ":" line[1]
    }
  }
  END {
    if (total == 0) {
      print "No coverage data for lib/ in '"$lcov"'."
      exit 1
    }
    printf "Covered %d of %d lines in lib/.\n", total - missed, total
    exit (missed > 0)
  }
' "$lcov"
